apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foundry-scout

resources:
  - namespace.yaml
  - cronjob.yaml
  - configmap.yaml
  - pvc.yaml
  - networkpolicy.yaml
  - deployment.yaml
  - service.yaml
  - external-secret.yaml

commonLabels:
  app.kubernetes.io/name: foundry-scout
  app.kubernetes.io/part-of: enclii

images:
  - name: foundry-scout
    newName: ghcr.io/madfam-org/foundry-scout
