apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-scout-data
  namespace: foundry-scout
  labels:
    app.kubernetes.io/name: foundry-scout
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
