version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gocritic

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
