apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- digest: sha256:5863a4e6529ca120ab6b0d0f3387ff338e3691c44382b4a32a34c230ebda9dbf
  name: ghcr.io/madfam-org/foundry-scout
  newName: ghcr.io/madfam-org/foundry-scout
