apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

images:
- digest: sha256:2f3268d4eb39ada2a6391294f9069739cc2727405d36f3a117de46049cbf56f5
  name: ghcr.io/madfam-org/foundry-scout
  newName: ghcr.io/madfam-org/foundry-scout
